<a href="https://colab.research.google.com/github/thatvivekhingu/Machine_learning/blob/main/08_Naive_Bias(Part_1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
df=pd.read_csv('titanic.csv')
df.head()

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0

In [6]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

   Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [10]:
target = df.Survived
inputs = df.drop('Survived',axis='columns')

In [11]:
df.head()

   Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [12]:
dummies = pd.get_dummies(inputs.Sex)
dummies.head()

   female   male
0   False   True
1    True  False
2    True  False
3    True  False
4   False   True

In [22]:
inputs.drop('Sex',axis='columns',inplace=True)
inputs.head()

   Pclass   Age     Fare  female   male
0       3  22.0   7.2500   False   True
1       1  38.0  71.2833    True  False
2       3  26.0   7.9250    True  False
3       1  35.0  53.1000    True  False
4       3  35.0   8.0500   False   True

In [15]:
inputs = pd.concat([inputs,dummies],axis='columns')
inputs.head()

   Pclass     Sex   Age     Fare  female   male
0       3    male  22.0   7.2500   False   True
1       1  female  38.0  71.2833    True  False
2       3  female  26.0   7.9250    True  False
3       1  female  35.0  53.1000    True  False
4       3    male  35.0   8.0500   False   True

In [17]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [18]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [21]:
inputs.Age=inputs.Age.fillna(inputs.Age.mean())
inputs.head()

   Pclass     Sex   Age     Fare  female   male
0       3    male  22.0   7.2500   False   True
1       1  female  38.0  71.2833    True  False
2       3  female  26.0   7.9250    True  False
3       1  female  35.0  53.1000    True  False
4       3    male  35.0   8.0500   False   True

In [39]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(inputs,target,test_size=0.2)

In [40]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()

In [41]:
model.fit(X_train,y_train)

GaussianNB()

In [43]:
model.score(X_test,y_test)

0.8044692737430168

In [44]:
X_test[:10]

     Pclass        Age      Fare  female   male
179       3  36.000000    0.0000   False   True
489       3   9.000000   15.9000   False   True
38        3  18.000000   18.0000    True  False
667       3  29.699118    7.7750   False   True
687       3  19.000000   10.1708   False   True
338       3  45.000000    8.0500   False   True
88        1  23.000000  263.0000    True  False
209       1  40.000000   31.0000   False   True
481       2  29.699118    0.0000   False   True
341       1  24.000000  263.0000    True  False

In [45]:
y_test[:10]

179    0
489    1
38     0
667    0
687    0
338    1
88     1
209    1
481    0
341    1
Name: Survived, dtype: int64

In [46]:
model.predict(X_test[:10])

array([0, 0, 1, 0, 0, 0, 1, 0, 0, 1])

In [47]:
model.predict_proba(X_test[:10])

array([[9.89903392e-01, 1.00966076e-02],
       [9.85281793e-01, 1.47182070e-02],
       [9.51218711e-02, 9.04878129e-01],
       [9.90243221e-01, 9.75677933e-03],
       [9.88665477e-01, 1.13345231e-02],
       [9.90243531e-01, 9.75646924e-03],
       [8.47987435e-13, 1.00000000e+00],
       [9.11486291e-01, 8.85137088e-02],
       [9.75934132e-01, 2.40658680e-02],
       [8.61865331e-13, 1.00000000e+00]])