<a href="https://colab.research.google.com/github/thatvivekhingu/Machine_learning/blob/main/Decision_Tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
data={
    'company':['google','google','google','google','google'],
    'job':['Sales','Sales','Business','Business','Computer programmer'],
    'degree':['BE','ME','BE','ME','BE'],
    'salary more than 100k':[0,0,1,1,0]
}

In [6]:
df=pd.DataFrame(data)
df

  company                  job degree  salary more than 100k
0  google                Sales     BE                      0
1  google                Sales     ME                      0
2  google             Business     BE                      1
3  google             Business     ME                      1
4  google  Computer programmer     BE                      0

In [7]:
input=df.drop('salary more than 100k',axis='columns')
input

  company                  job degree
0  google                Sales     BE
1  google                Sales     ME
2  google             Business     BE
3  google             Business     ME
4  google  Computer programmer     BE

Change string to number

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
le_company=LabelEncoder()
le_job=LabelEncoder()
le_degree=LabelEncoder()

In [12]:
input['comapnay_n']= le_company.fit_transform(input['company'])
input['job_n']=le_job.fit_transform(input['job'])
input['degree_n']=le_degree.fit_transform(input['degree'])

In [13]:
input.head()

  company                  job degree  comapnay_n  job_n  degree_n
0  google                Sales     BE           0      2         0
1  google                Sales     ME           0      2         1
2  google             Business     BE           0      0         0
3  google             Business     ME           0      0         1
4  google  Computer programmer     BE           0      1         0

In [14]:
input_n=input.drop(['company','job','degree'],axis='columns')
input_n

   comapnay_n  job_n  degree_n
0           0      2         0
1           0      2         1
2           0      0         0
3           0      0         1
4           0      1         0

In [15]:
## preduction via decision tree

In [16]:
from sklearn import tree

In [17]:
model=tree.DecisionTreeClassifier()

In [21]:
model.fit(input_n,df['salary more than 100k'])

DecisionTreeClassifier()

In [23]:
model.predict([[2,2,1]]) # google=2 sales=2 me=1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0])

In [24]:
# more than 100k salry in google of ME degree student '0'

In [25]:
model.predict([[0,0,0]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])